server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1d23xxlwwfo3sjm3o.mysql.rds.aliyuncs.com:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: songtx
    password: Songtianxiao0620

#mybatis
mybatis:
  mapper-locations:
    -classpath:mybatisMapper/*.xml
  type-aliases-package:
    com.wss.templateproject.model


#通用mapper配置
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
#是否判断字符串类型 !=''
  notEmpty: true
  identity: MYSQL

#分页插件
#pagehelper.helperDialect=mysql
#pagehelper.reasonable=true
#pagehelper.supportMethodsArguments=true
#pagehelper.params=count=countSql
