server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1d23xxlwwfo3sjm3o.mysql.rds.aliyuncs.com:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: songtx
    password: Songtianxiao0620
  redis:
    host: 60.205.182.126   # Redis服务器地址
    database: 0  #Redis数据库索引(默认为0)
    port: 6379 #Redis服务器连接端口
    password:  #Redis服务器连接密码(默认为空)
    jedis:
      pool:
        max-active: 8 #连接池最大连接数(使用负值表示没有限制)
        max-wait: -1ms #连接池最大阻塞等待时间(使用负值表示没有限制)
        max-idle: 8 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
    timeout: 10000ms #连接超时时间(毫秒)

#mybatis
mybatis:
  mapper-locations:
    classpath*:mybatisMapper/*.xml
  type-aliases-package:
    com.wss.templateproject.model


#通用mapper配置
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
#是否判断字符串类型 !=''
  notEmpty: true
  identity: MYSQL

#自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120000 #验证码超期时间

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

#分页插件
#pagehelper.helperDialect=mysql
#pagehelper.reasonable=true
#pagehelper.supportMethodsArguments=true
#pagehelper.params=count=countSql

